apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookinventory
  labels:
    app: bookinventory
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bookinventory
  template:
    metadata:
      labels:
        app: bookinventory
    spec:
      containers:
        - name: bookinventory
          image: cnaacr.azurecr.io/cna-bookstore-bookinventory:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/bookinventory'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/bookinventory'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
